name: CI Test

on:
  push:
    paths:
      - '.github/workflows/ci-test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "CI works"
